spring.application.name=job-app
spring.datasource.url=jdbc:postgresql://postgres:5432/job-app
spring.datasource.username=Mahindra
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.oauth2.client.registration.google.client-id=225146574445-cp5i6n0ab003h4kfmb2ofl1dhc5e54gt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email