spring.application.name=job-app
spring.datasource.url=jdbc:postgresql://jobapp.c5ks0umma6kz.us-east-2.rds.amazonaws.com:5432/job-app-data
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.oauth2.client.registration.google.client-id=225146574445-cp5i6n0ab003h4kfmb2ofl1dhc5e54gt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
